PUT http://lejnet/api/json/
content-type: application/json

{"file": "csnet/announce_test.json","data":"<p>これはテストデータです</p>"}

###
PUT http://localhost:3000/json
content-type: application/json

{"file": "csnet/announce_test.json","data":"<p>これはテストです。</p>"}
###
GET http://lejnet/api/json
content-type: application/json

{"file": "csnet/announce.json"}
###
POST http://lejnet/api/csnet/web-order
###
GET http://localhost:3000/excel/wo-tracking/
###
GET http://lejnet/api/excel/wo-tracking/