GET http://lejnet/api/oracle/

###
POST http://lejnet/api/oracle/smlr_item
content-type: application/json

{ "color_code": "ZTU"}
###
POST http://localhost:3000/oracle/smlr_item
content-type: application/json

{ "color_code": "ZTU"}
###
PUT http://lejnet/api/json/
content-type: application/json

{"file": "csnet/announce.json","data":"<p>これはテストデータです</p>"}

###
PUT http://localhost:3000/json
content-type: application/json

{"file": "csnet/announce_test.json","data":"THIS IS TEST DATA"}
###
GET http://lejnet/api/json
content-type: application/json

{"file": "csnet/announce.json"}
###
POST http://lejnet/api/csnet/web-order