PUT http://lejnet/api/json/
content-type: application/json

{"file": "csnet/announce_test.json","data":"<p>これはテストデータです</p>"}
###
POST http://lejnet/api-test/csnet/rakugae_tracking/
content-type: application/json

{"cust_num": "205455"}

###
POST http://localhost:3001/csnet/sample_item/